services:
#  rabbitmq:
#    image: 'rabbitmq:latest'
#    environment:
#      - 'RABBITMQ_DEFAULT_PASS=secret'
#      - 'RABBITMQ_DEFAULT_USER=myuser'
#    ports:
#      - '5673'
#    networks:
#      - network-example

# Use postgres/example user/password credentials
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynet

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8085:8080
    networks:
      - mynet

volumes:
  postgres-data:

networks:
  mynet:
